version: '3'
name: 'sentinelstream'

services:
  data_producer:
    build:
      context: ./data_producer
    environment:
      API_GATEWAY_URL: 'http://fastapi_app:8000/transactions/'

  test:
    build:
      dockerfile: ./tests/Dockerfile
    depends_on:
      - data_producer


