version: '3'
name: 'sentinelstream'

services:
  api_gateway:
    build:
      context: ./api
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka1:19092,kafka2:19093,kafka3:19094'
      KAFKA_TOPIC: 'transaction_topic'

  test:
    build:
      dockerfile: ./tests/Dockerfile
