version: '3'
name: 'sentinelstream'

services:
  ingestion: 
    build:
      context: data_ingestion
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '4040:4040'

  test:
    build:
      dockerfile: ./tests/Dockerfile
